---
title: "nowcast-analysis"
author: "Ega Kurnia Yazid"
format: html
editor: visual
execute: 
  echo: false
---

## A. Import Libraries and Dataset

### 0. Installing Packages (if have not)

```{r installing-packages}
#install.packages("tidyverse")
#install.packages("dplyr")
#install.packages("tidyr")
#install.packages("midasr")
#install.packages("ggplot2")
#install.packages("sandwich")
#install.packages("quantreg")
#install.packages("SparseM")
#install.packages("httr")
#install.packages("jsonlite")
#install.packages("modelsummary")
#install.packages("markdown")
#renv::snapshot() # Freeze requirements
```

### 1. Importing Libraries

```{r importing-libraries}
library(tidyverse)
library(midasr)
library(ggplot2)
library(modelsummary)
library(markdown)
```

### 2. Importing Dataset

```{r importing-dataset-api}
#apikey <- Sys.getenv("APIKEY")
#ceic_html <- "https://api.ceicdata.com/v2/insights/series/cfca6d08-c231-497b-8aa2-b8fc370a0763,b3b0bb75-1058-4527-b8e6-5ea05595cb10,ba5be73a-0dab-4b15-be88-4805ebb739fe?lang=en&format=json&token="

# Connect to API
#idxenergy <- httr::GET(paste(ceic_html, apikey, sep=""))

# Check Status
#str(idxenergy)

# Content to JSON
#energycontent <- httr::content(idxenergy, as="text")

# JSON to Table
#energyJSON <- jsonlite::fromJSON(energycontent)

# View JSON
```

```{r importing-dataset-local}

# Import stock-market data
stockmarket   <- read.csv("dataset/stock-market.csv")
monetary      <- read.csv("dataset/monetary-dataset.csv", sep = ";") 
                # might drop rgdp and unemployment

# Import national mobility data

# Import fuel consumption data
fuel          <- read.csv("dataset/fuel-consumption.csv", sep=";")

# Filter data when idxenergy & idxtrans get started consistently
stockdata <- data.frame(stockmarket) %>% 
  slice_tail(n=826)

# Renaming Columns
colnames(stockdata) <- c("date", "idxenergy", "idxtrans", "jkse")
```

### 3. Raw Dataset Formatting

```{r date-formatting}
# Date Formatting
stockdata$date     <- as.Date(stockdata$date, format = "%m/%d/%Y")

monetary$date <- paste0(monetary$date, "/01") %>% 
  as.Date(monetary$date, format = "%m/%Y/%d") %>% 
  format("%m/%d/%Y") %>% 
  as.Date(monetary$date, format = "%m/%d/%Y")

fuel$date     <- paste0(fuel$date, "-01") %>% 
  as.Date(fuel$date, format="%b-%y-%d") %>% 
  format("%m/%d/%Y") %>%
  as.Date(fuel$date, format = "%m/%d/%Y")
```

### 4. Merge Datasets

```{r merge-dataset}
# Merge all Data
data <- stockdata %>% 
  left_join(monetary, by="date") %>% 
  left_join(fuel, by="date")
```

## B. Descriptive Statistics

```{r}
# Data Summary
summary(data)
```

```{r correlation-stats}
datasummary_correlation(data)
```

## C. Nowcasting

```{r}
set.seed(2024)
fit <- midas_r(data$RON8890 ~ mls(data$idxtrans, 0:29, 30), start=NULL)
```
